POST http://localhost:8080/api/events
Content-Type: application/json; charset=UTF-8

{
  "name": "Atomic 동시성 테스트",
  "capacity": 100,
  "strategy": "ATOMIC",
  "openAt": "2026-09-01T00:00:00",
  "closeAt": "2026-12-31T23:59:59"
}
